"use client";

import {
  Document,
  Page,
  View,
  Text,
  StyleSheet,
} from "@react-pdf/renderer";
import type { FormField, FormSubmission } from "@/lib/data/types";

const styles = StyleSheet.create({
  page: {
    padding: 40,
    fontFamily: "Helvetica",
    fontSize: 11,
    color: "#111",
  },
  header: {
    marginBottom: 24,
    borderBottomWidth: 2,
    borderBottomColor: "#F26430",
    paddingBottom: 12,
  },
  brand: {
    fontSize: 18,
    fontWeight: "bold",
    color: "#0B1F3A",
  },
  title: {
    fontSize: 14,
    fontWeight: "bold",
    marginTop: 4,
    color: "#333",
  },
  meta: {
    marginTop: 12,
    marginBottom: 8,
    fontSize: 10,
    color: "#555",
  },
  row: {
    flexDirection: "row",
    borderBottomWidth: 1,
    borderBottomColor: "#eee",
    paddingVertical: 8,
  },
  labelCell: {
    width: "40%",
    fontWeight: "bold",
    color: "#0B1F3A",
  },
  valueCell: {
    width: "60%",
  },
  footer: {
    position: "absolute",
    bottom: 40,
    left: 40,
    right: 40,
    fontSize: 8,
    color: "#999",
    borderTopWidth: 1,
    borderTopColor: "#eee",
    paddingTop: 8,
  },
});

export function SubmissionPdfDocument({
  submission,
  fields,
}: {
  submission: FormSubmission;
  fields: FormField[];
}) {
  function labelFor(key: string): string {
    const field = fields.find((f) => f.key === key);
    return field?.label ?? key.replace(/([A-Z])/g, " $1").trim();
  }

  function display(key: string): string {
    const value = submission.data[key];
    if (value === null || value === undefined || value === "") return "—";
    if (typeof value === "boolean") return value ? "Yes" : "No";
    if (typeof value === "object") return JSON.stringify(value);
    return String(value);
  }

  const keys = Object.keys(submission.data);

  return (
    <Document title={`${submission.template_name ?? "Application"} Submission`}>
      <Page size="A4" style={styles.page}>
        <View style={styles.header}>
          <Text style={styles.brand}>Go Gro Mobility</Text>
          <Text style={styles.title}>
            {submission.template_name ?? "Application Form"} — Submission
          </Text>
        </View>

        <Text style={styles.meta}>
          Client: {submission.full_name ?? "—"} | Email: {submission.email ?? "—"}
        </Text>
        <Text style={styles.meta}>
          Status: {submission.status} |
          Submitted:{" "}
          {submission.submitted_at
            ? new Date(submission.submitted_at).toLocaleString("en-ZA")
            : "—"}
        </Text>

        {keys.map((key) => (
          <View key={key} style={styles.row}>
            <Text style={styles.labelCell}>{labelFor(key)}</Text>
            <Text style={styles.valueCell}>{display(key)}</Text>
          </View>
        ))}

        {keys.length === 0 ? (
          <Text style={{ color: "#666" }}>No answers recorded.</Text>
        ) : null}

        <Text style={styles.footer}>
          Submission ID: {submission.id} | Generated by Go Gro Mobility
        </Text>
      </Page>
    </Document>
  );
}